name: Pytest

on: [push]

jobs:
  custom-logging:
    env:
      working_directory: ./src
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      working-directory: ${{ env.working_directory }}
      run: |
        poetry install --no-root
    - name: Running tests
      working-directory: ${{ env.working_directory }}
      run: |
        poetry run pytest
